const BASE_ACTION = './item';
export const GET_ITEM = `${BASE_ACTION}/GET_ITEM`;
export const ADD_TO_CART = `${BASE_ACTION}/ADD_TO_CART`;
export const FETCH_RESPONSE = `${BASE_ACTION}/FETCH_RESPONSE`;
export const FETCH_REQUEST = `${BASE_ACTION}/FETCH_REQUEST`;
export const FETCH_ERROR_RESPONSE = `${BASE_ACTION}/FETCH_ERROR_RESPONSE`;
