const BASE_ACTION = './payment';
export const SUBMIT = `${BASE_ACTION}/SUBMIT`;
export const CARD_VALIDATE = `${BASE_ACTION}/CARD_VALIDATE`;
export const FETCH_RESPONSE = `${BASE_ACTION}/FETCH_RESPONSE`;
export const FETCH_REQUEST = `${BASE_ACTION}/FETCH_REQUEST`;
export const FETCH_ERROR_RESPONSE = `${BASE_ACTION}/FETCH_ERROR_RESPONSE`;
