const BASE_ACTION = './summary';
export const FETCH_RESPONSE = `${BASE_ACTION}/FETCH_RESPONSE`;
export const FETCH_REQUEST = `${BASE_ACTION}/FETCH_REQUEST`;
export const FETCH_ERROR_RESPONSE = `${BASE_ACTION}/FETCH_ERROR_RESPONSE`;
